# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SearchMode <- function(mat, bg_mean, bg_sd, K, max_iter, tol, p, q, theta1, sigma1) {
    .Call('riso_SearchMode', PACKAGE = 'riso', mat, bg_mean, bg_sd, K, max_iter, tol, p, q, theta1, sigma1)
}

calLikeIso <- function(mat, p, q, bg_mean, bg_sd, theta1, sigma1) {
    .Call('riso_calLikeIso', PACKAGE = 'riso', mat, p, q, bg_mean, bg_sd, theta1, sigma1)
}

count_bins <- function(counts, bins) {
    .Call('riso_count_bins', PACKAGE = 'riso', counts, bins)
}

